import Post from "@/src/components/common/Post";

export const ENGLocalizedStrings = {
  Public: {
    All: "All",
    Confirm: "Confirm",
    Cancel: "Cancel",
    Back: "Back",
    Save: "Save",
    Close: "Close",
    Language: "Language: English",
    Post: "Post",
    Friend: "Friend",
    Username: "Username",
    About: "About",
    Today: "Today, what do you want to do?",
    Detail: "Detail",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    LogOut: "Log Out",
    SetingProfile: "Setting Profile",
    Mail: "Email",
    Phone: "Phone Number",
    Birthday: "Birth Date", 
    Active: "Created Date", 
    FriendFind: "Friend Find",
    FriendView: "View All Friend",
    Conform: "Confirm", 
    LogoutConfirm: "Are you sure you want to log out?",
    More: "More",
    AddFriend: "Add Friend",
    ReportFriend: "Report",
    Block: "Block",
    Vietnamese: "Vietnamese",
    English: "English",
    ErrorFetchingProfile: "Error fetching profile!",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Password",
      FamilyName: "Family Name",
      Name: "Name",
      Phone: "Phone Number",
      BirthDay: "Birth Date",
      GetOTP: "Enter OTP",
      OTP: "OTP Code",
      ConfirmPassword: "Confirm Password",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Please enter family name!",
      NameRequiredMessage: "Please enter name!",
      PhoneRequiredMessage: "Please enter phone number!",
      BirthDayRequiredMessage: "Please select a birth date!",
      EmailRequiredMessage: "Please enter email!",
      PasswordRequiredMessage: "Please enter password!",
      ConfirmPasswordRequiredMessage: "Please confirm your password!",
      AgreeRequiredMessage: "Please agree to the terms!",
      OTPRequiredMessage: "Please enter OTP code!",
      OTPPressRequiredMessage: "Please receive OTP code!",
    },
    TypeMessage: {
      EmailTypeMessage: "Invalid email!",
      PasswordTypeMessage: "Password must be over 8 characters!",
      ConfirmPasswordTypeMessage: "Confirm password is invalid!",
      OTPTypeMessage: "OTP code must be a 6-digit string!",
      PhoneTypeMessage: "Phone number must be a 10-digit string!",
    }
  },
  Login: {
    LoginButton: "Login",
    ForgotPasswordText: "Forgot password?",
    DontHaveAccout: "Don't have an account?",
    SignUpNow: "Sign up now!",
    Or: "Or",
    LoginFailed: "Login failed!"
  },
  SignUp: {
    SignUpButton: "Sign up",
    SignUpSuccess: "Sign up successful! Please log in again",
    SignUpFailed: "Sign up failed!",
    OTPSuccess: "OTP has been sent successfully!",
    OTPAlreadySent: "OTP has been sent and is valid for 10 minutes!",
    OTPFailed: "Sending OTP failed!",
    AlreadyHaveAccount: "Already have an account?",
    LoginNow: "Log in now!",
    AgreePolicies: "I agree to the YourVibes terms",
  }
}