export const VnLocalizedStrings = {
  Public: {
    All: "Tất cả",
    Confirm: "Xác nhận",
    Cancel: "Hủy",
    Back: "Quay lại",
    Save: "Lưu",
    Close: "Đóng",
    Language: "Ngôn ngữ: Tiếng Việt",
    Post:"Bài Viết",
    Friend: "Bạn Bè",
    Username: "Tên người dùng",
    About: "Giới Thiệu",
    Today: "Hôm nay bạn thế nào?",
    Detail: "Chi tiết",
    EditProfile: "Chỉnh sửa trang cá nhân",
    ChangePassword: "Thay đổi mật khẩu",
    LogOut: "Đăng xuất",
    SetingProfile: "Cài đặt trang cá nhân",
    Mail: "Email",
    Phone: "Số điện thoại",
    Birthday: "Ngày sinh",
    Active: "Ngày tham gia",
    FriendFind: "Tìm bạn bè",
    FriendView: "Xem tất cả bạn bè",
    Conform: "Xác nhận",
    LogoutConfirm: "Bạn có chắc chắn muốn đăng xuất",
    More: "Xem thêm",
    AddFriend: "Kết Bạn",
    ReportFriend: "Báo Cáo",
    Block: "Chặn",
    Vietnamese: "Tiếng Việt",
    English: "Tiếng Anh",
    ErrorFetchingProfile: "Lỗi hiển thị thông tin",
    Biography: "Giới thiệu",
    UnknownUser: "Người dùng YourVibes",
    Public: "Công khai",
    Everyone: "Mọi người",
    Private: "Chỉ mình tôi",
    MinuteAgo: "phút trước",
    HourAgo: "giờ trước",
    DayAgo: "ngày trước",
    Action: "Hành động",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Mật khẩu",
      FamilyName: "Họ",
      Name: "Tên",
      Phone: "Số điện thoại",
      BirthDay: "Ngày sinh",
      GetOTP: "Nhập OTP",
      OTP: "Mã OTP",
      ConfirmPassword: "Xác nhận mật khẩu",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Vui lòng nhập họ!",
      NameRequiredMessage: "Vui lòng nhập tên!",
      PhoneRequiredMessage: "Vui lòng nhập số điện thoại!",
      BirthDayRequiredMessage: "Vui lòng chọn ngày sinh!",
      EmailRequiredMessage: "Vui lòng nhập email!",
      PasswordRequiredMessage: "Vui lòng nhập mật khẩu!",
      ConfirmPasswordRequiredMessage: "Vui lòng xác nhận mật khẩu!",
      AgreeRequiredMessage: "Vui lòng đồng ý các điều khoản!",
      OTPRequiredMessage: "Vui lòng nhập mã OTP!",
      OTPPressRequiredMessage: "Vui lòng nhận mã OTP!",
    },
    TypeMessage: {
      EmailTypeMessage: "Email không hợp lệ!",
      PasswordTypeMessage: "Mật khẩu phải trên 8 kí tự!",
      ConfirmPasswordTypeMessage: "Xác nhận mật khẩu không hợp lệ!",
      OTPTypeMessage: "Mã OTP phải là chuỗi 6 số!",
      PhoneTypeMessage: "Số điện thoại phải là chuỗi 10 số!",
    }
  },
  Login: {
    LoginButton: "Đăng nhập",
    ForgotPasswordText: "Quên mật khẩu?",
    DontHaveAccout: "Bạn chưa có tài khoản?",
    SignUpNow: "Đăng ký ngay!",
    Or: "Hoặc",
    LoginFailed: "Đăng nhập thất bại!"
  },
  SignUp: {
    SignUpButton: "Đăng ký",
    SignUpSuccess: "Đăng ký thành công! Vui lòng đăng nhập lại",
    SignUpFailed: "Đăng ký thất bại!",
    OTPSuccess: "OTP đã được gửi thành công!",
    OTPAlreadySent: "Mã OTP đã được gửi và tồn tại trong 10 phút!",
    OTPFailed: "Gửi OTP thất bại!",
    AlreadyHaveAccount: "Bạn đã có tài khoản?",
    LoginNow: "Đăng nhập ngay!",
    AgreePolicies: "Tôi đồng ý các điều khoản của YourVibes",
  },
  AddPost: {
    NewPost: "Bài đăng mới",
    WhatDoYouThink: "Bạn đang nghĩ gì?",
    PrivacyText: "Bài đăng sẽ được chia sẻ với",
    PostNow: "Đăng ngay",
    CreatePostSuccess: "Đăng bài thành công!",
    CreatePostFailed: "Đăng bài thất bại!",
    EmptyContent: "Thiếu nội dung hoặc file media",
    PickImgFailed: "Tải file thất bại!"
  },
  ObjectPostPrivacy: {
    PublicDescription: 'Bất kỳ ai ở trên YourVibes',
    FriendDescription: 'Chỉ bạn bè của bạn ở trên YourVibes',
    PrivateDescription: 'Chỉ bạn có thể nhìn thấy',
    PostPrivacy: "Đối tượng của bài viết",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy bài viết của bạn?",
      CanFind: "Bài viết của bạn có thể hiện thị trên trang cá nhân và trong kết quả tìm kiếm.",
      DefaultPrivacy1: "Tuy đối tượng mặc định là ",
      DefaultPrivacy2: ", nhưng bạn có thể thay đổi đối tượng của riêng bài viết này."
    },
    ChoosePrivacy: "Chọn Đối tượng"
  },
  Post: {
    EditPost: "Chỉnh sửa bài đăng",
    EditPrivacy: "Chỉnh sửa quyền riêng tư",
    DeletePost: "Xóa bài đăng",
    Advertisement: "Quảng cáo bài đăng",
    ReportPost: "Báo cáo bài đăng",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Lấy danh sách bài viết thất bại!",
      GetOnePostFailed: "Lấy bài viết thất bại!"
    }
  },
  UpdatePost: {
    UpdatePostSuccess: "Cập nhật bài đăng thành công!",
    UpdatePostFailed: "Cập nhật bài đăng thất bại!",
  },
  DeletePost: {
    DeleteConfirm: "Bạn chắc chắn muốn xóa bài viết này?",
    DeleteSuccess: "Xóa bài viết thành công!",
    DeleteFailed: "Xóa bài viết thát bại!"
  }
}